### ISSUE TITLE
hello，if I want to improve it ,how can I modify which parts 

### ISSUE THREAD

**Issue by powers8** [FilippoBotti/Mask_RCNN#1]
hello，if I want to improve it ,how can I modify which parts

**Comment by FilippoBotti** [comment]
Give me more info about what you want to do because there could be a lot of way to improve it

**Comment by powers8** [comment]
thank you for your response, and I could consult you in my future research

**Comment by FilippoBotti** [comment]
Yes, open issue when you have problem with this repo

**Comment by powers8** [comment]
May I ask if your model can only accept coco type data as input ？

**Comment by FilippoBotti** [comment]
You can use your own dataset type but you need to modify the dataloader in order to use it.
Fork the repo and then change dataset/modanet.py dataloader with your dataloader

**Comment by powers8** [comment]
hello，I want to fine tuning the fpn， how can I do? I can't find any details about the implementation of FPN.
